### PR TITLE
Rest api/events

### PR DESCRIPTION
**Pull request by yoonsiko**
Check over the serializer

### CODE REVIEW

**Comment by yoonsiko** [comment]
Is it necessary with generics.RetrieveUpdateDestroyAPIView in the views file and obj.get_absolute_all()?

**Review by Geirhov — APPROVED** [review]
All the information is nicely displayed in the API, we might need to add an api site for each event aswell. I.e arrangementer/api/social/1, dont know what the convention is on that, but it should not be much of a hassle to add it later.

**Review by Geirhov — CHANGES_REQUESTED** [review]
The bedpresregistration and socialregistration serializers are missing a user=UserSerializer() field.

**Review by Geirhov — APPROVED** [review]
Fire pull-request my man, keep up the good work!

**Pull request merged**
